package com.aiep.ene.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EgresosDiariosAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEgresosDiariosAllPropertiesEquals(EgresosDiarios expected, EgresosDiarios actual) {
        assertEgresosDiariosAutoGeneratedPropertiesEquals(expected, actual);
        assertEgresosDiariosAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEgresosDiariosAllUpdatablePropertiesEquals(EgresosDiarios expected, EgresosDiarios actual) {
        assertEgresosDiariosUpdatableFieldsEquals(expected, actual);
        assertEgresosDiariosUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEgresosDiariosAutoGeneratedPropertiesEquals(EgresosDiarios expected, EgresosDiarios actual) {
        assertThat(expected)
            .as("Verify EgresosDiarios auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEgresosDiariosUpdatableFieldsEquals(EgresosDiarios expected, EgresosDiarios actual) {
        assertThat(expected)
            .as("Verify EgresosDiarios relevant properties")
            .satisfies(e -> assertThat(e.getGastoDiario()).as("check gastoDiario").isEqualTo(actual.getGastoDiario()))
            .satisfies(e -> assertThat(e.getValorGasto()).as("check valorGasto").isEqualTo(actual.getValorGasto()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEgresosDiariosUpdatableRelationshipsEquals(EgresosDiarios expected, EgresosDiarios actual) {
        // empty method
    }
}
