package com.aiep.ene.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IngresosDiariosAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngresosDiariosAllPropertiesEquals(IngresosDiarios expected, IngresosDiarios actual) {
        assertIngresosDiariosAutoGeneratedPropertiesEquals(expected, actual);
        assertIngresosDiariosAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngresosDiariosAllUpdatablePropertiesEquals(IngresosDiarios expected, IngresosDiarios actual) {
        assertIngresosDiariosUpdatableFieldsEquals(expected, actual);
        assertIngresosDiariosUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngresosDiariosAutoGeneratedPropertiesEquals(IngresosDiarios expected, IngresosDiarios actual) {
        assertThat(expected)
            .as("Verify IngresosDiarios auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngresosDiariosUpdatableFieldsEquals(IngresosDiarios expected, IngresosDiarios actual) {
        assertThat(expected)
            .as("Verify IngresosDiarios relevant properties")
            .satisfies(e -> assertThat(e.getVentaNumero()).as("check ventaNumero").isEqualTo(actual.getVentaNumero()))
            .satisfies(e -> assertThat(e.getValorVenta()).as("check valorVenta").isEqualTo(actual.getValorVenta()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngresosDiariosUpdatableRelationshipsEquals(IngresosDiarios expected, IngresosDiarios actual) {
        // empty method
    }
}
