package com.aiep.ene.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PedidosProveedoresAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidosProveedoresAllPropertiesEquals(PedidosProveedores expected, PedidosProveedores actual) {
        assertPedidosProveedoresAutoGeneratedPropertiesEquals(expected, actual);
        assertPedidosProveedoresAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidosProveedoresAllUpdatablePropertiesEquals(PedidosProveedores expected, PedidosProveedores actual) {
        assertPedidosProveedoresUpdatableFieldsEquals(expected, actual);
        assertPedidosProveedoresUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidosProveedoresAutoGeneratedPropertiesEquals(PedidosProveedores expected, PedidosProveedores actual) {
        assertThat(expected)
            .as("Verify PedidosProveedores auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidosProveedoresUpdatableFieldsEquals(PedidosProveedores expected, PedidosProveedores actual) {
        assertThat(expected)
            .as("Verify PedidosProveedores relevant properties")
            .satisfies(e -> assertThat(e.getProducto()).as("check producto").isEqualTo(actual.getProducto()))
            .satisfies(e -> assertThat(e.getCantidad()).as("check cantidad").isEqualTo(actual.getCantidad()))
            .satisfies(e -> assertThat(e.getValor()).as("check valor").isEqualTo(actual.getValor()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidosProveedoresUpdatableRelationshipsEquals(PedidosProveedores expected, PedidosProveedores actual) {
        // empty method
    }
}
